services:
  - type: web
    name: berlin-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: X_USERNAME
        sync: false
      - key: X_PASSWORD
        sync: false
      - key: BSKY_HANDLE
        sync: false
      - key: BSKY_APP_PASSWORD
        sync: false
      - key: GIST_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
