name: Update VIZ state

on:
  schedule:
    - cron: "*/5 * * * *"  # alle 5 Minuten
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install selenium webdriver-manager beautifulsoup4
      - run: python botscraper.py
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add state.json
          git diff --quiet && exit 0
          git commit -m "Update state.json"
          git push
